select a.CALENDAR_DATE as date,a.SECURITY_CODE as "証券CD",a.KANJI_NAME as "銘柄",m.PRICE as "株価"
from NPMDB_test.NQIUSER1.ATTRIBUTES A
left join NPMDB_test.NQIUSER1.MARKET M on 
 a.CALENDAR_DATE=m.CALENDAR_DATE and
 a.SECURITY_ID=m.SECURITY_ID
 where a.SECURITY_CODE='1301'
 and m.APPRAISAL_ID=1
 and a.CALENDAR_DATE between 20220101 and 20221231  
 order by a.CALENDAR_DATE;
