select a.CALENDAR_DATE as CALENDAR_DATE,a.SECURITY_CODE as SECURITY_CODE ,a.KANJI_NAME as KANJI_NAME
from NPMDB_test.NQIUSER1.ATTRIBUTES A
 where a.SECURITY_CODE='1301'
 and a.CALENDAR_DATE between 20220101 and 20221231  
 order by a.CALENDAR_DATE;
